### ISSUE TITLE
asn1ber: OID values starting larger than .2.39 are interpreted incorrectly

### ISSUE THREAD

**Issue by gregmac** [calmh/node-snmp-native#28]
OID values are encoded a bit strangely in asn1, in that the first two octets are encoded using a single byte:

> BER encoding. Primitive. Contents octets are as follows, where value1, …, valuen denote the integer values of the components in the complete object identifier:
>
> 1. The first octet has value 40 × value1 + value2. (This is unambiguous, since value1
is limited to values 0, 1, and 2; value2 is limited to the range 0 to 39 when value1 is 0 or 1; and, according to X.208, n is always at least 2.)
> 2. The following octets, if any, encode value3, …, valuen. Each value is encoded base 128, most significant digit first, with as few digits as possible, and the most significant bit of each octet except the last in the value's encoding set to "1."

The result of this is that the first two octets of an OID can only be within the ranges:

* 0.0.x to 0.39.x
* 1.0.x to 1.39.x
* 2.0.x to 2.79.x

The OID value `.2.46` encodes to the byte `0x7E`. The problem is this is incorrectly decoded as `.3.6`. 

I came across this with a device with a `hrDeviceId` value. Interestingly, this is actually a fairly common problem across a few different libraries and applications, and took a while to isolate because *many* other libraries/tools have the same bug

**Comment by calmh** [comment]
I wonder if ITU are real happy with the tradeoff in terms of man hours fixing stuff like this versus the one byte saved in the encoding...

**Comment by calmh** [comment]
See, I even managed to confuse myself in the commit message.

**Comment by gregmac** [comment]
Yeah this can be summed up as: Don't be "clever". Especially when designing protocols. 

Thanks for the fix!
