### ISSUE TITLE
infinite getNext() in getSubtree()

### ISSUE THREAD

**Issue by Excelight** [calmh/node-snmp-native#38]
I've one switch with some problem. When I use the getSubtree() api to fetch the switch's ifOperStatus, it cannot stop. Then I look into the code, found that it called getNext() infinitely, cause of the varbinds[0].value is null which has not been considered.

Here is the response of the switch when I call it use the snmpgetnext command:
```
$>snmpgetnext -v 2c -c xxx xx.xx.xx.xx ifOperStatus.60
Error in packet.
Reason: (genError) A general failure occured
Failed object: IF-MIB::ifOperStatus.60
```

**Comment by calmh** [comment]
Right, we should of course stop iterating on an error...
