### ISSUE TITLE
Broken buffer for ".1.3.6.1.2.1.2.2.1.6" (if address)

### ISSUE THREAD

**Issue by dr-dimitru** [calmh/node-snmp-native#41]
Expected: `c8:60:0:df:8:61`
Got:
```js
{ 
  type: 4,
  value: '�`\u0000�\ba',
  oid: [ 1, 3, 6, 1, 2, 1, 2, 2, 1, 6, 2 ],
  valueRaw: <Buffer c8 60 00 df 08 61>,
  valueHex: 'c86000df0861', // Decoded HEX is 졠ßࡡ
  requestId: 502795267,
  receiveStamp: 1458171248188,
  sendStamp: 1458171248131
}
```

Response from `snmpwalk`:
```shell
IF-MIB::ifPhysAddress.2 = STRING: c8:60:0:df:8:61
```

Code:
```js
session.getSubtree({
  oid: '.1.3.6.1.2.1.2.2.1.6'
}, function(error, varbinds) {
  if (!error && varbinds.length) {
    varbinds.forEach(function(vb) {
      console.log(vb);
    });
  }
});
```

Or am I doing something wrong?

**Comment by calmh** [comment]
snmpwalk is being smart here, as the returned data is an octet-string with the (binary) contents `c8 60 00 df 08 61` (the MAC address), which you see in the valueRaw and valueHex fields. You probably want to use one of those directly.

**Comment by dr-dimitru** [comment]
Not a problem at all with:
```js
valueHex.match(/.{1,2}/g).join(':');
```

But it just doesn't seems right, as it exactly return a *__string__*: `IF-MIB::ifPhysAddress.2 = STRING: c8:60:0:df:8:61`

**Comment by calmh** [comment]
It doesn't, snmpwalk is simplifying things for you. The actual type returned according the MIB is a `PhysAddress`:

```
PhysAddress ::=
    OCTET STRING
-- This data type is used to model media addresses.  For many
-- types of media, this will be in a binary representation.
-- For example, an ethernet address would be represented as
-- a string of 6 octets.
```

The actual octet string returned is not `"c8:60:0:df:8:61"`, it is the six bytes `c8 60 00 df 08 61`.

**Comment by dr-dimitru** [comment]
@calmh Thank you for explanation, appreciated.
