### ISSUE TITLE
Getting always a timeout

### ISSUE THREAD

**Issue by hoigo** [calmh/node-snmp-native#46]
I've just try to test snmp-native, but I always got a timeout executing a simple "get" (SNMP agent running on 173 under 127.0.0.1 with community "public"). Do you have any hints?

**Comment by bangert** [comment]
does it work with snmpget from the commandline or a different client? can you show us your code?

**Comment by hoigo** [comment]
It was my fault. I've tried to request an agent which supports only SNMP v1.
