### ISSUE TITLE
NPM out of sync with Github

### ISSUE THREAD

**Issue by robertcrowe** [calmh/node-snmp-native#56]
'npm install snmp-native' installs a different version of the module compared to what is on Github.  I don't know how many differences there are, but there is one that causes problems for me:

/lib/snmp.js, line 801/807:

if (options.combinedTimeout) {
        var combinedTimeoutEvent = function() {
            combinedTimeoutExpired = true;
            return callback(new Error('Timeout'), **results**);
        };
        combinedTimeoutTimer = setTimeout(combinedTimeoutEvent, options.combinedTimeout);
    }

The results parameter in the callback should be vbs.  This was fixed back in January, so it makes me wonder how old the NPM code is.

**Comment by calmh** [comment]
I've pushed a 1.1.1

**Comment by robertcrowe** [comment]
Perfect, thanks for the quick response!
