### ISSUE TITLE
Can't resolve 'dgram'

### ISSUE THREAD

**Issue by froston** [calmh/node-snmp-native#61]
Hi, 
when trying to import snmp-native (using webpack) ...
`import snmp from 'snmp-native'` or 
`const snmp = require('snmp-native')`
... throws this error:
`ModuleNotFoundError: Module not found: Error: Can't resolve 'dgram' in '... node_modules/snmp-native/lib'`
Thanks for any help!

**Comment by bangert** [comment]
This only works in nodejs, which provides dgram...

https://nodejs.org/api/dgram.html

**Comment by froston** [comment]
thanks, yeah I was trying to use it in browser
