### ISSUE TITLE
Unable to install the pacakage

### ISSUE THREAD

**Issue by PantTushar** [calmh/node-snmp-native#67]
Guys,

When I run the npm command i.e. npm install snmp-native it gives the following error - 

"Unable to resolve module `assert` from `/Users/tushar-pant/Documents/WWW-ReactNative/node_modules/snmp-native/lib/snmp.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968

To resolve try the following:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

What should be the issue?

**Comment by bangert** [comment]
I find the error message, which is not from snmp-native by the way, pretty clear. Which part is it you want help with, and why do you think we would be able to help you?

**Comment by PantTushar** [comment]
Thanks! 
why do you think we would be able to help you? - I am just trying to use the common library for android and ios through RN and hence referring to this library. Otherwise i have to go the native way and write the code for both. Would appreciate if you support this otherwise all good.

**Comment by calmh** [comment]
Your install not having the assert module is not related to this package. I suspect it is react related. Pursue the lead in the error message etc.

**Comment by PantTushar** [comment]
Thank You!
